### ISSUE TITLE
Support Neovide

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#111]
### Question or Suggestion

I've found a couple of issues working with neovide and cyberdream

1. telescope background color is black (not transparent anymore)
2. when moving cursor back and fort between trouble document symbols and editor, the editor loses its transparency
3. vim.notify is no longer transparent
4. mini.files is no longer transparent
5. Executing `:Lazy` now lost its transparency (it has a black background)
6. The bullet point above is applicable when executing `:Mason`

**Comment by scottmckendry** [comment]
Hello @idelice 🙂 

It looks like this is known shortcoming of the Neovide project. These and all other related transparency problems should be resolved when [this RFC](https://github.com/neovide/neovide/issues/2471) and it's child items are implemented.

Until then, I'm not sure if there's anything we can do with cyberdream.nvim to combat these. If you go through the linked issues, you may be able to find some suitable workarounds.

Once the issue is resolved, we could probably document some sensible default settings to pair with Neovide to achieve certain looks.
