### ISSUE TITLE
Extension contribution

### ISSUE THREAD

**Issue by gldtn** [scottmckendry/cyberdream.nvim#116]
### Question or Suggestion

Hello @scottmckendry , I would like to contribute with [Neogit](https://github.com/NeogitOrg/neogit) extension but I'm not totally sure how to do it as I'm not very good at managing github repos. I followed the instructions on contributing page, but what is the best way to go about it and submit a PR? Should I clone your repo, make the changes and submit a PR? Currently for testing purpose I edit the nvim file directly, which I'm sure it not the correct way to do it.

Thanks for your patience!

**Comment by scottmckendry** [comment]
Thanks for showing interest in the project @gldtn! I want the contribution process to be as streamlined as possible so it's always good to get feedback from first-time contributors.

If you use lazy.nvim as you neovim plugin you can configure it to look for local copies of plugins in a specific folder, like I have done here:

https://github.com/scottmckendry/Windots/blob/eec6734e91d556b203f765d3bb6b9fc2f9fb5f49/nvim/lua/core/lazy.lua#L21C5-L24C7

From the [configuration docs](https://lazy.folke.io/configuration):
> ```lua
>dev = {
>    ---@type string | fun(plugin: LazyPlugin): string directory where you store your local plugin projects
>    path = "~/projects",
>   ---@type string[] plugins that match these patterns will use your local versions instead of being fetched from GitHub>
>    patterns = {}, -- For example {"folke"}
>    fallback = false, -- Fallback to git when local plugin doesn't exist
>}
>```

Once this is setup, you can clone your fork of cyberdream.nvim to the local directory you've configured in lazy.nvim. 

Then in your plugin config, add `dev = true,` to get lazy to load your local copy instead of it's own cloned version.

Here's an example from my config:

https://github.com/scottmckendry/Windots/blob/eec6734e91d556b203f765d3bb6b9fc2f9fb5f49/nvim/lua/plugins/colourscheme.lua#L4C9-L4C20

This will let you test your changes locally before committing/merging upstream. Let me know if you have any other questions!

**Comment by gldtn** [comment]
I think I did everything right, and submitted a PR 🎉 

Thanks for you help!

Dev would not work until I added the imports inside specs table:

```lua
spec = {
        { import = "plugins" },
        { import = "plugins.lsp" },
    },
```

before I just had:
```lua
 { import = "plugins" },
        { import = "plugins.lsp" },
```

Leaving it registered here just in case someone has the same problem.
