### ISSUE TITLE
Overrides merge with default properties instead of completely overriding

### ISSUE THREAD

**Issue by scottmckendry** [scottmckendry/cyberdream.nvim#123]
Originally reported by @zackAJ here:

https://github.com/scottmckendry/cyberdream.nvim/commit/abc44e40e3141899e57a5c87c3a5191dc1d55930#commitcomment-145481445

Overrides are merging properties with the values that they are overriding. In most cases this is fine, but it requires you to explicitly set values like `link`, `bold`, `sp` etc. to get the desired result when these are already set.

This will likely result in a breaking change - I suspect some configs out in the wild that rely on the current merge behaviour. However, this kind of defaults the purpose of an "override" IMO.

**Comment by zackAJ** [comment]
I believe this is the expected behavior @scottmckendry
from what I noticed in code bases `vim.tbl_deep_extend()` is used where the values are required for example the setup config of a package, you can't trust a user that might pass an empty table.
while `vim.tbl_extend()` is used for optional configurations that the program could run without (just like an `extension`)

**Comment by scottmckendry** [comment]
Agreed, extending the table deeper than the first level in this case doesn't make much sense. I've looked back through the code and can see I've had this logic for at least 7 months now. Long before v1.0.0 was released. But I can't think why I would have chosen deep_extend over a regular extend at the time. Guess we'll never know 🤷

Thanks for reporting this one, @zackAJ 🙂
