### ISSUE TITLE
Feature request: add lighten and darken util

### ISSUE THREAD

**Issue by gldtn** [scottmckendry/cyberdream.nvim#146]
### Question or Suggestion

I'm in the middle of reworking the neogit theme for cyberdream and need to use a darker color of red/green in git diff bg. I'm trying to avoid hard coding a specific color, so I remembered that tokyonight has a util where we can lighten/darken any of the theme colors. His util for that can be found here: https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/util.lua

This would allow a little more of flexibility without having to add additional colors to theme itself.. 

Which you can call it anywhere you need it with:
```lua
local util = require("tokyonight.util")
highlight = { fg = util.lighten(colors.red1, 0.3) } -- number between 0 and 1. 0 results in white, 1 results in red1
```

I thought maybe it would be a good idea to implement something similar to cyberdream.

Also a quick question, is it ok to set global variables in the extension, like so:
```lua
local base = {
        txt1 = t.fg,
        txt2 = t.bgHighlight,
        bg1 = t.bg,
        bg2 = t.bgAlt,
        bg3 = t.bgHighlight,
}
local accent = {
        p1 = t.orange,
        p2 = t.green,
        p3 = t.blue,
        p4 = t.red,
        s1 = t.cyan,
        s2 = t.pink,
        s3 = t.magenta,
        s4 = t.yellow,
        s5 = t.purple,
}
```

So I can reference it in the actual highlights?
```lua
 local highlights = {
        NeogitNormal = { bg = base.bg1 },
        NeogitStatusHEAD = { bg = base.bg1 },
        NeogitFold = { fg = base.txt1 },
        NeogitRemote = { fg = accent.s1 },
        NeogitBranch = { fg = accent.s2, bold = true },
        NeogitBranchHead = { fg = accent.s1, bold = true },
        NeogitWinSeparator = { fg = base.bg3, bg = t.bg1 },
        NeogitChangeDeleted = { fg = accent.p4, bold = true, italic = true },
        NeogitChangeModified = { fg = accent.s1, bold = true, italic = true },
        NeogitSectionHeader = { fg = accent.p1, bold = true },
        NeogitCommitViewHeader = { fg = accent.p1, bg = base.bg3 },
}
```

Thanks!

**Comment by scottmckendry** [comment]
Hey @gldtn!

Thanks for the feedback 🙂 I think most of what you're trying to do can be achieved without too much effort.

> util where we can lighten/darken any of the theme colors

I already do something very similar with [blend](https://github.com/scottmckendry/cyberdream.nvim/blob/7e6feb49d2ec47a742215754ec0ecc51eebba55a/lua/cyberdream/util.lua#L169) which takes in two colours and a weight in order to generate new colours. You can blend an existing colour with `fg` or `bg` to lighten or darken it. 

One of the main reasons I prefer this approach is because the same highlight will darken/lighten dynamically based on whether the user is using the `light` or `dark` variant. 

For example, lightening a foreground colour in dark mode won't have much impact on it's readability. In light mode, you risk lowering contrast to the point where text becomes difficult to read.

For diffs, I recommend linking to the already defined [`Diff...` groups](https://github.com/scottmckendry/cyberdream.nvim/blob/7e6feb49d2ec47a742215754ec0ecc51eebba55a/lua/cyberdream/extensions/base.lua#L19-L22) that already use the `blend` function. You can see an example of this [here in gitsigns.lua](https://github.com/scottmckendry/cyberdream.nvim/blob/7e6feb49d2ec47a742215754ec0ecc51eebba55a/lua/cyberdream/extensions/gitsigns.lua#L14-L16).

> is it ok to set global variables in the extension

Yes, since these are actually locals not globals 😉

However, the example you provided doesn't make a whole lot of sense to me. What benefit does this provide aside from a slightly shorter name for some colours? It makes it harder to tell what colour is being used when looking at the highlights.

**Comment by gldtn** [comment]
> For example, lightening a foreground colour in dark mode won't have much impact on it's readability. In light mode, you risk lowering contrast to the point where text becomes difficult to read.

That makes sense.

> For diffs, I recommend linking to the already defined [`Diff...` groups](https://github.com/scottmckendry/cyberdream.nvim/blob/7e6feb49d2ec47a742215754ec0ecc51eebba55a/lua/cyberdream/extensions/base.lua#L19-L22) that already use the `blend` function. You can see an example of this [here in gitsigns.lua](https://github.com/scottmckendry/cyberdream.nvim/blob/7e6feb49d2ec47a742215754ec0ecc51eebba55a/lua/cyberdream/extensions/gitsigns.lua#L14-L16).

The problem is that Neogit don't use a separate highlight for text color, so I would need to  use nvim_get_hl to set fg/bg as far as I know.

So I ended up just using the blend util, something like:
```lua
NeogitDiffAdd = {
            fg = util.blend(t.bg_solid, t.green, 0.3),
            bg = util.blend(t.bg_solid, t.green, 0.8),
        },
```

Unless you can think of a more clever way.. 

> Yes, since these are actually locals not globals 😉

Lol I meant locals, thanks!
 
> However, the example you provided doesn't make a whole lot of sense to me. What benefit does this provide aside from a slightly shorter name for some colours? It makes it harder to tell what colour is being used when looking at the highlights.

While you are right it's currently acting more of a schema, especially since I'm still testing out to see what colors works best. This way If I want to test everything with a different background color I don't have to alter each individual highlight, I can just change the bg variable above.

Another question, how do you reload highlights without exiting nvim? I tried a few things, but no luck. Do you use autocmds or anything to help you out?

**Comment by scottmckendry** [comment]
Ah, right. Understood! 

There is `.lazy.lua` which adds some QoL features for development like colour previews and hot reloading. You'll need to be using `lazy.nvim` as your package manager for it to work properly. 

You would have seen a prompt like this after cloning the repo and opening it for the first time:
![image](https://github.com/user-attachments/assets/aef46900-666c-4d6a-90b0-3ca1af6e61cd)

You can get it to reappear by changing something in the file, like adding a comment etc.

**Comment by gldtn** [comment]
Awesome, thanks for all your help.
