### ISSUE TITLE
Question: is there a way to make the indent blanklines less visible?

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#29]
Right now, they are so bright in my opinion that it's distracting.

How can I make them less visible?

<img width="116" alt="Screenshot 2024-05-01 at 11 45 50" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/47226f35-5181-4acd-ac26-f83363889901">

**Comment by scottmckendry** [comment]
I've added support for indent-blankline.nvim in the latest commit. Let me know what you think.

I've intentionally not set the `IblWhitespace` highlight group. Mainly because I think anything other than transparent is kind of ugly looking. If you want to set this, you can do it either directly in your IBL config or in the cyberdream theme highlight overrides table in the setup function.
