### ISSUE TITLE
Entire mini.nvim, vim-fugitive and fzf-lua support

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#81]
### Question or Suggestion

Can support for entire mini.nvim suite and fzf-lua be added. Currently this theme doesn't support mini.statusline, mini.indentscope afaik.

**Comment by scottmckendry** [comment]
Hi @231tr0n!
Thanks for raising the issue. I'll be adding support for fzf-lua very soon :)

**Comment by scottmckendry** [comment]
Hello @echasnovski!

Hope I'm not being too cheeky asking this of you, but I can see you've made contributions to several other colorschemes just in the last day. I thought I'd jump on the opportunity to see if you'd be interested in adding _Offical Mini Support™_ to cyberdream.nvim as well. Would love input from the original author!

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/e88a4e9b-4203-4945-9602-de16fdb3869e)

**Comment by scottmckendry** [comment]
@231tr0n I've added a borderless theme for fzf-lua that looks like this:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/4802d6de-6de8-4abe-8728-1a989d190e9a)

This mimics the default telescope theme quite closely. For it to look correct, you need to set `fzf_colors` to `true` in your fzf config. E.g. 
```lua
return {
    "ibhagwan/fzf-lua",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    config = function()
        require("fzf-lua").setup({
            fzf_colors = true,
        })
    end,
}
```

**Comment by 231tr0n** [comment]
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/a52e845a-1854-4cd6-85a7-69ec735d3bb6)
@scottmckendry, Is support for vim-fugitive possible. I did not want to create a new defect. So I modified the existing one.

**Comment by echasnovski** [comment]
> Hello @echasnovski!
> 
> Hope I'm not being too cheeky asking this of you, but I can see you've made contributions to several other colorschemes just in the last day. I thought I'd jump on the opportunity to see if you'd be interested in adding _Offical Mini Support™_ to cyberdream.nvim as well. Would love input from the original author!


Hi @scottmckendry!

Since you are the first one to ask this (and nicely so), [here you go](https://github.com/scottmckendry/cyberdream.nvim/pull/86). I'd like to explicitly stress though, that this is not an _Offical Mini Support™_, but my attempt to make 'mini.nvim' experience more pleasant for users. I'd much rather enjoy seeing that color scheme authors or their users add this kind of support on their own (it is explicitly stated as a [welcome way to contribute to 'mini.nvim'](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md#contributing) with an [explicit list of highlight groups needed for full support](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md#list-of-highlight-groups)).

------

I would also like to give some feedback for issues that were apparent when adding 'mini.nvim' support:
- The `Visual` highlight group defines both foreground and background. This is generally ok (although I prefer background only), but the result has way too low contrast ratio ([1.71, to be exact](https://www.siegemedia.com/contrast-ratio#%2316181a-on-%233c4048)). To the point that text is barely readable.
- Having [`Diff*` highlight only through foreground](https://github.com/scottmckendry/cyberdream.nvim/blob/ba05f56f9f1e2a08d1acf8952b5a209a2268842c/lua/cyberdream/theme.lua#L61-L64) is rarely a good choice for usability. Mostly because they are used to highlight already highlighted text. Using background highlighting is usually a better choice. I'd prefer something like what is used for `MiniDiffOverXxx` highlight groups in PR.
- The `CursorLine` and `CursorColumn` highlight groups define lines used to quickly locate cursor on screen. As cursor can be used in floating windows, it is reasonable to have those two groups be such that they are visible both in normal and floating windows. Hence I am not really sure what the purpose of [custom `MiniFilesCursorLine`](https://github.com/scottmckendry/cyberdream.nvim/blob/ba05f56f9f1e2a08d1acf8952b5a209a2268842c/lua/cyberdream/extensions/mini.lua#L13) is.
- I'd personally create all shades with appropriate names beforehand instead of using `util.blend()` in the highlight group definitions. This allows for a more coherent future definitions in plugin extensions.

Hope this helps.

**Comment by scottmckendry** [comment]
You're a ⭐ @echasnovski! Thanks for the excellent feedback. Especially around useability and contrast. I want the colorscheme to be as friendly as possible for users and contributors alike. 

Appreciate all your hard work on neovim and mini! It's people like you that make the neovim community such a pleasure to be a part of 💚

**Comment by scottmckendry** [comment]
@231tr0n I've fixed the highlights for vim-fugitive's `:Git diff` command in the latest commit. As far as I can tell, everything else looks pretty good out of the box. If you spot anything else, let me know 🙂

**Comment by 231tr0n** [comment]
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/2945e209-79a1-4aaa-8321-889951852e53)
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/393d05fe-dc8b-4bf4-a4f5-dcdbd9070eef)
@scottmckendry The mini.statusline and MiniHiPatterns dont look properly with the latest changes.
MiniHipatternsNote
MiniHipatternsTodo
MiniHipatternsHack
MiniHipatternsHack
MiniStatuslineModeReplace
MiniStatuslineModeCommand
MiniStatuslineModeInsert
MiniStatuslineModeVisual
MiniStatuslineModeNormal
MiniStatuslineModeOther
are the related highlight groups afaik.

**Comment by scottmckendry** [comment]
Should be resolved now. Pretty sure this would only be an issue when transparency is enabled - due to the `bg` color being set to "NONE". Let me know if the most recent change fixes it 👍🏻

**Comment by 231tr0n** [comment]
> Should be resolved now. Pretty sure this would only be an issue when transparency is enabled - due to the `bg` color being set to "NONE". Let me know if the most recent change fixes it 👍🏻

@scottmckendry yup it fixes it. One last addon, currently if we open buffers horizontally using :split command, there is visually no seperator spearating the two buffers horizontally. Vertically there is a line but my doubt was can something be done about this horizontally.
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/1d98549d-85e4-4863-a3fb-7ea76817fd32)

**Comment by scottmckendry** [comment]
Oh, that's an easy one! Just set `hide_fillchars` to `false` (or remove the option entirely since this is the default) in your config and the separators will reappear 🙂 

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/964bac24-54d9-4665-ba6c-f37bee1c29fa)

**Comment by 231tr0n** [comment]
> Oh, that's an easy one! Just set `hide_fillchars` to `false` (or remove the option entirely since this is the default) in your config and the separators will reappear 🙂
> 
> ![image](https://private-user-images.githubusercontent.com/39483124/344335256-964bac24-54d9-4665-ba6c-f37bee1c29fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MTcwMjQsIm5iZiI6MTcxOTYxNjcyNCwicGF0aCI6Ii8zOTQ4MzEyNC8zNDQzMzUyNTYtOTY0YmFjMjQtNTRkOS00NjY1LWJhNmMtZjM3YmVlMWMyOWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDIzMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMDI1YzNiOTFhOWVmNjY5YWU2OWI4NjlhNTVkNjhhMmE3N2Y1ODUzYzBhY2EwYmQ1NDE5ZWMyNjkxNTQ4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLvJjF_Oj2kOUU1GzvgxFEEPNc73Crm5lc3cNTM2ARo)

It is false in my case but still i dont see any separators horizontally.

**Comment by scottmckendry** [comment]
Hmmm... I'm not 100% sure what that could be then. Could you try defining the fillchar manually in your config?
This line [here](https://github.com/231tr0n/config/blob/main/nvim/init.lua#L114), update it to `vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:,horiz:─]]` to see if there's any change.

If not, it might be getting overridden somewhere else.

**Comment by 231tr0n** [comment]
> Hmmm... I'm not 100% sure what that could be then. Could you try defining the fillchar manually in your config? This line [here](https://github.com/231tr0n/config/blob/main/nvim/init.lua#L114), update it to `vim.o.fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:,horiz:─]]` to see if there's any change.
> 
> If not, it might be getting overridden somewhere else.

It is still the same even after the change you suggested.The thing is vertical line is coming, only horizontal is the issue.
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/977c8fba-2321-4a1a-8cab-ca51259ddb3e)

**Comment by scottmckendry** [comment]
Looks like it might be a global statusline thing. If you run `:set laststatus=3` does that fix it?

**Comment by 231tr0n** [comment]
> Looks like it might be a global statusline thing. If you run `:set laststatus=3` does that fix it?

Yup this fixes it. Thank you soo much @scottmckendry.

**Comment by 231tr0n** [comment]
CLosing this issue.

**Comment by echasnovski** [comment]
> You're a ⭐ @echasnovski! Thanks for the excellent feedback. Especially around useability and contrast. I want the colorscheme to be as friendly as possible for users and contributors alike.
> 
> Appreciate all your hard work on neovim and mini! It's people like you that make the neovim community such a pleasure to be a part of 💚

You're welcome! Best of luck keeping up with the not-always-easy burden of maintaining a color scheme.

------

> * Having [`Diff*` highlight only through foreground](https://github.com/scottmckendry/cyberdream.nvim/blob/ba05f56f9f1e2a08d1acf8952b5a209a2268842c/lua/cyberdream/theme.lua#L61-L64) is rarely a good choice for usability. Mostly because they are used to highlight already highlighted text. Using background highlighting is usually a better choice. I'd prefer something like what is used for `MiniDiffOverXxx` highlight groups in PR.

I've remembered the other (probably more prominent) reason why `Diff*` highlight groups usually have distinctive background. `DiffAdd`, `DiffChange`, and `DiffDelete` are used to highlight *whole lines*, meaning the part after end of line is also highlighted. If there is no background attribute in those highlight groups, this is not visible. And there is also an issue of highlighting whitespace with these groups.

**Comment by scottmckendry** [comment]
I've just added a fix for this in the latest commit. Gave it a spin with diffview.nvim and it looks SOO much better! Thank you again 🙂
