### ISSUE TITLE
Tree sitter highlighting differs a bit

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#84]
### Description

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/3a4a3ff7-d346-43ce-8b4c-9ba232be2301)
If you compare both the themes, you can see that vim.o.wrap differs between both the themes probably due to a missing highlight group for treesitter. Do you know which highlight group could this be.

### Neovim version?

NVIM v0.11.0-dev-313+gfc9b70826

### What should happen?

In vim.o.wrap, o.wrap part should be highlighted as well.

### What happened instead?

In vim.o.wrap, o.wrap part should was not highlighted.

### Your configuration

```Lua
{
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            transparent = true,
            italic_comments = true,
            hide_fillchars = true,
            borderless_telescope = true,
        })
        vim.cmd("colorscheme cyberdream")
    end,
}
```

**Comment by scottmckendry** [comment]
Hello @231tr0n! Thanks for submitting 🙂 

This is mostly intentional as a lot of the variable subtypes for tree-sitter and LSP highlight groups link back to their parent. In this case, the groups you're referencing in the screenshot are `@variable.member` (tree-sitter) and `@lsp.type.property` (LSP).

You can override both of these groups in your config with your desired color. For example:

```lua
 {
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            transparent = true,
            italic_comments = true,
            hide_fillchars = true,
            borderless_telescope = true,
            theme = {
                overrides = function(colors)
                    return {
                        -- Change these to your liking
                        ["@variable.member"] = { fg = colors.cyan },
                        ["@lsp.type.property"] = { fg = colors.cyan },
                    }
                end,
            },
        })
        vim.cmd("colorscheme cyberdream")
    end,
}
```

The result looks like this:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/966117e5-9de2-4789-b08e-6f94bf0c1a3f)

If you want to customise other groups, but you're not sure what they're called, you can use `:Inspect` while your cursor is on the token lookup which groups are being applied:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/eb576968-2145-4c37-ba08-1835b50795ed)

I hope this helps!

**Comment by 231tr0n** [comment]
Yup. This helps. Thank you for helping me out.

**Comment by 231tr0n** [comment]
@scottmckendry just a small query like can you let me know what all treesitter and lsp highlight groups are linked.

**Comment by scottmckendry** [comment]
@231tr0n certainly!

If you run `:hi` in Neovim, a window will open with _all_ of the highlight groups currently defined. You'll notice there's a LOT!

You can also run `:lua require("fzf-lua").highlights()` to show all of these in fzf:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/aa5d009e-44d9-414e-9588-cb2e63783ab3)

Telescope also supports this with `:Telescope highlights`.
